# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'SELFH'

steps:
- task: DownloadPipelineArtifact@1
  inputs:
    buildType: 'current'
    targetPath: '$(Pipeline.Workspace)'


- task: Terraform@2
  inputs:
    TemplatePath: './modules'
    Arguments: 'init'
    PlanPath: './modules'
    InstallTerraform: true
    UseAzureSub: false
